######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 2 16:01:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

include (../matrixLib.pri)
