######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 19 20:10:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
	problemData.h \
	alphaFunc.h \
	betaFunc.h

SOURCES += main.cpp \
	alphaFunc.cpp \
	betaFunc.cpp


include (../matrixLib.pri)
include (../integralLib.pri)
