######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 11 21:46:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += problemData.h ../matrixLib/matrix.h ../matrixLib/matrix.tcc
SOURCES += main.cpp
