######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 7 16:44:39 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
