######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 12 17:59:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
