######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 17 19:44:02 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += matrix.h matrix2x2.h matrix.tcc
SOURCES += main.cpp
