######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 20 01:54:51 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += function.h interval.h
SOURCES += interval.cpp main.cpp
