######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 13 16:08:52 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
