######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 15 17:11:36 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    mainwindow.cpp \
    inverseFunctionInterpolation.cpp \
    interval.cpp

HEADERS += \
    mainwindow.h \
    inverseFunctionInterpolation.h \
    interval.h

FORMS += \
    mainwindow.ui







