######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 4 19:39:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += funcInterpolation.h funcInterpolation.tcc
SOURCES += main.cpp
